#!/bin/bash
# Setting up firewall on web-01

# Set default policies first
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports (after setting default policies)
sudo ufw allow 22/tcp    # SSH
sudo ufw allow 80/tcp    # HTTP
sudo ufw allow 443/tcp   # HTTPS

# Enable UFW
sudo ufw --force enable

