#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
# Adds custom X-Served-By header with hostname.

# Update package list and install Nginx
sudo apt-get update 
sudo apt-get install -y nginx 

# Create index page
echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure redirect
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default

# Add custom header X-Served-By with hostname
# shellcheck disable=SC2154
sudo sed -i "/server_name _;/a\\        add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Test configuration and restart
sudo nginx -t
sudo service nginx restart
