#!/usr/bin/env bash
# Sets up a custom 404 page in Nginx

apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx
service nginx restart
